config/routes.rb
Beermap::Application.routes.draw do
  resources :locations

  resources :breweries, :defaults => { :format => 'json' }

  resources :beers

  resources :main, :path => "/" do
    collection do 
      get :about
      get :update, :path => "/update"
      post :upload
    end
  end

  

end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base

	def self.update_location
		@updates = Brewery.where('lat is null')
		@updates.each do |brew|
			location = Geocoder.search(brew.address + " " + brew.city + " " + brew.postcode + " " + brew.country).first.data
			brew.lat = location['geometry']['location']['lat']
			brew.lon = location['geometry']['location']['lng']
			brew.save
			puts brew.lat
			puts brew.lon
		end
	end
end

app/models/function.rb
class Function < ActiveRecord::Base
	
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :ibu, :abv, :desc, :brewery_id)
    end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :desc, :lat, :lon, :city, :state, :country, :food, :tour, :address, :seasonal, :take_home, :postcode)
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render action: 'show', status: :created, location: @location }
      else
        format.html { render action: 'new' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:brewery_id, :name, :address, :lat, :lon)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
   
   USER_ID, PASSWORD = ENV['UPDATE_UN'], ENV['UPDATE_PW']
 
   # Require authentication only for edit and delete operation
   before_filter :authenticate, :only => [ :update  ]

	def index
		Brewery.update_location
		@city = "Portland Oregon"
		@location = Geocoder.search(@city).first.data
		@lat = @location['geometry']['location']['lat']
		@lon = @location['geometry']['location']['lng']
		@breweries = Brewery.where('city = ?','Portland')
		puts @breweries.count
	end
	def about

	end
	def update
	end
	def upload
    require 'csv' 
    filename = File.open(params[:file].path, "r:ISO-8859-1")
    CSV.read(filename, "r:windows-1250", :headers => true).each do |row|
    	brew = Brewery.where('name = ?', row['name'])
    	unless brew.empty?
        brew = brew.first
        row.each do |a|
          brew.instance_variable_get('@'+a[0])
          brew.send(a[0].downcase.gsub('_','')+'=', a[1])
        end
        brew.save
	    else
	    	brew = Brewery.new
        row.each do |a|
          brew.instance_variable_get('@'+a[0])
          brew.send(a[0].downcase.gsub('_','')+'=', a[1])
        end
        brew.save()
	    end
    end
	end

	private
   def authenticate
      authenticate_or_request_with_http_basic do |id, password| 
          id == USER_ID && password == PASSWORD
      end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ibu %><br>
    <%= f.number_field :ibu %>
  </div>
  <div class="field">
    <%= f.label :abv %><br>
    <%= f.text_field :abv %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= f.text_field :brewery_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Ibu</th>
      <th>Abv</th>
      <th>Desc</th>
      <th>Brewery</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @beers.each do |beer| %>
      <tr>
        <td><%= beer.name %></td>
        <td><%= beer.ibu %></td>
        <td><%= beer.abv %></td>
        <td><%= beer.desc %></td>
        <td><%= beer.brewery_id %></td>
        <td><%= link_to 'Show', beer %></td>
        <td><%= link_to 'Edit', edit_beer_path(beer) %></td>
        <td><%= link_to 'Destroy', beer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @beer.name %>
</p>

<p>
  <strong>Ibu:</strong>
  <%= @beer.ibu %>
</p>

<p>
  <strong>Abv:</strong>
  <%= @beer.abv %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @beer.desc %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @beer.brewery_id %>
</p>

<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_area :desc %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :food %><br>
    <%= f.check_box :food %>
  </div>
  <div class="field">
    <%= f.label :tour %><br>
    <%= f.check_box :tour %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :seasonal %><br>
    <%= f.check_box :seasonal %>
  </div>
  <div class="field">
    <%= f.label :take_home %><br>
    <%= f.check_box :take_home %>
  </div>
  <div class="field">
    <%= f.label :postcode %><br>
    <%= f.text_field :postcode %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>City</th>
      <th>State</th>
      <th>Country</th>
      <th>Food</th>
      <th>Tour</th>
      <th>Address</th>
      <th>Seasonal</th>
      <th>Take home</th>
      <th>Postcode</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @breweries.each do |brewery| %>
      <tr>
        <td><%= brewery.name %></td>
        <td><%= brewery.desc %></td>
        <td><%= brewery.lat %></td>
        <td><%= brewery.lon %></td>
        <td><%= brewery.city %></td>
        <td><%= brewery.state %></td>
        <td><%= brewery.country %></td>
        <td><%= brewery.food %></td>
        <td><%= brewery.tour %></td>
        <td><%= brewery.address %></td>
        <td><%= brewery.seasonal %></td>
        <td><%= brewery.take_home %></td>
        <td><%= brewery.postcode %></td>
        <td><%= link_to 'Show', brewery %></td>
        <td><%= link_to 'Edit', edit_brewery_path(brewery) %></td>
        <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brewery', new_brewery_path %>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @brewery.desc %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @brewery.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @brewery.lon %>
</p>

<p>
  <strong>City:</strong>
  <%= @brewery.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @brewery.state %>
</p>

<p>
  <strong>Country:</strong>
  <%= @brewery.country %>
</p>

<p>
  <strong>Food:</strong>
  <%= @brewery.food %>
</p>

<p>
  <strong>Tour:</strong>
  <%= @brewery.tour %>
</p>

<p>
  <strong>Address:</strong>
  <%= @brewery.address %>
</p>

<p>
  <strong>Seasonal:</strong>
  <%= @brewery.seasonal %>
</p>

<p>
  <strong>Take home:</strong>
  <%= @brewery.take_home %>
</p>

<p>
  <strong>Postcode:</strong>
  <%= @brewery.postcode %>
</p>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Beermap</title>
	<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_KEY"] %>&sensor=true"></script>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container">
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="#">Beerlandia</a>
	    </div>
	    <div class="collapse navbar-collapse">
	      <ul class="nav navbar-nav">
	        <li><a href="#about">About</a></li>
	      </ul>
	    </div><!--/.nav-collapse -->
	  </div>
	</div>
	<div id="container" class="container">
		<%= yield %>
	</div>
	<div id="footer">
	  <div class="container">
	    <p class="text-muted credit">Example courtesy <a href="http://martinbean.co.uk">Martin Bean</a> and <a href="http://ryanfait.com/sticky-footer/">Ryan Fait</a>.</p>
	  </div>
	</div>
	<script><%= yield :vars %></script>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<script><%= yield :script %></script>
	
</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= f.number_field :brewery_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lon %><br>
    <%= f.text_field :lon %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <thead>
    <tr>
      <th>Brewery</th>
      <th>Name</th>
      <th>Address</th>
      <th>Lat</th>
      <th>Lon</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.brewery_id %></td>
        <td><%= location.name %></td>
        <td><%= location.address %></td>
        <td><%= location.lat %></td>
        <td><%= location.lon %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Brewery:</strong>
  <%= @location.brewery_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @location.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @location.lon %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/main/about.html.erb
Hola

app/views/main/index.html.erb
<div id="map" class="google-maps">
	
</div>
<div style="margin-top:275px;">
  <div id="brewery">
    <h1 class="title"></h1>
    <div class="description"></div>
    <div class="seasonal" style="display:none">Seasonal Beer</div>
    <div class="food" style="display:none">Food</div>
  </div>
  <button class="btn btn-primary return" style="display:none;">Back</button>
</div>
<% content_for :vars do %>
	var startLat = <%= @lat %>;
	var startLon = <%= @lon %>;
<% end %>
<% content_for :script do %>
	<% @breweries.each do |b| %>
		addBrewery("<%= b.name %>",<%= b.lat %>,<%= b.lon %>,<%= b.id %>, "brewery")
	<% end %>
<% end %>

app/views/main/update.html.erb
<%= form_tag({:controller => "main", :action => 'upload', :method=> :post}, {:multipart => true}) do  %>
  <%= label_tag "File" %>
  <%= file_field_tag "file" %>
  <%= submit_tag "Update Breweries" %>
<% end %>